apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-config
  namespace: ecommerce
data:
  RABBITMQ_DEFAULT_USER: "user"
  RABBITMQ_DEFAULT_PASS: "password"
  RABBITMQ_ERLANG_COOKIE: "secret-cookie" 