apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-init
  namespace: ecommerce
data:
  init.js: |
    db.auth(process.env.MONGO_INITDB_ROOT_USERNAME, process.env.MONGO_INITDB_ROOT_PASSWORD)
    db = db.getSiblingDB('ecommerce')
    
    db.createUser({
      user: process.env.MONGODB_USERNAME,
      pwd: process.env.MONGODB_PASSWORD,
      roles: [
        { role: "readWrite", db: "ecommerce" }
      ]
    }) 